version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD='postgres'
    networks:
      - macacoweb

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - .:/receiver-wt-pokemon-mq
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - macacoweb

networks:
  macacoweb:
    external: 
      name: wt-pokemon-mq_macacoweb
    
